### PR TITLE
feat(schema): add microdata schema for author and blog posts

### PR DESCRIPTION
**Pull request by ramboz**
- Add helper method to quickly set several attributes on the same element
- Add BlogPosting schema to all blog cards
- Add Person and BlogPosting schema to single post pages

### CODE REVIEW

**Comment by rofe** [comment]
Can we add rich media (embeds) to the schema?

**Comment by ramboz** [comment]
@rofe Sure! Would you have some reference pages to validate this against?

**Comment by rofe** [comment]
@ramboz try https://microdata-schema--theblog--adobe.hlx.page/en/drafts/embed-test.html

**Comment by ramboz** [comment]
@rofe Thanks! Perfect :)

Couple comments:
- this is missing a vimeo embed example
- this is missing "split banner" embeds I've seen when browsing some articles. not sure if these are HTML embeds or other

For video embeds, Google expects:
- name
- description
- upload date
- thumbnail

to properly render them as rich search results. I can fake some and leave the rest empty, but ideally we should think about a way to provide those in the markup

**Comment by rofe** [comment]
> * this is missing a vimeo embed example

Oh yes, it is missing a lot of things 😄  [Here](https://github.com/adobe/helix-pipeline/blob/2620c8e41d7079967bcd800b261cf2369fcbbc12/docs/secrets-properties-embed_allowlist.md) are the kinds `helix-pipeline` allows (we keep adding to that list as theblog requires them, iframely supports a whole lot more).

> * this is missing "split banner" embeds I've seen when browsing some articles. not sure if these are HTML embeds or other

Sounds like a blog specific layout component based on a Word table... Do you have an example URL? But in any case the layouting shouldn't matter for the microdata, unless I'm missing something.

> For video embeds, Google expects:
> 
> * name
> * description
> * upload date
> * thumbnail
> 
> to properly render them as rich search results. I can fake some and leave the rest empty, but ideally we should think about a way to provide those in the markup

+1

We just [added titles to iframes](https://github.com/adobe/helix-embed/issues/286). Can you create a `helix-embed` issue (or PR) for the others? @MarquiseRosier may have some ideas, too.

**Comment by ramboz** [comment]
> But in any case the layouting shouldn't matter for the microdata, unless I'm missing something.

Layouting, no. But content type does. At least if we want to proper specific schema (AudioObject, VideoObject, DigitalDocument, etc.) otherwise everything falls back to a generic CreativeWork.

**Comment by ramboz** [comment]
Some examples below:

**Internal Promotion**
_CreativeWork_
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/31/merkle-ceo-shifting-marketing-budgets-priorities-covid19.html#gs.eoitac
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/24/4-steps-to-foster-a-growth-mindset-and-improve-your-teams-i-can-attitude.html#gs.eoitaa
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/17/max-2020-registration-is-officially-open.html#gs.eoitjr (ideally should be https://schema.org/Event)
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/13/smb-playbook-for-customer-experience-management.html#gs.eoitlb (ideally should be https://schema.org/Event)
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/09/01/artist-lauren-hom-multiplies-her-creative-power-with-pdfs.html#gs.eogzi0 (ideally should be https://schema.org/SoftwareApplication)
- https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/09/02/how-epsilon-distributed-design-teams-collaborate-with-xd.html#gs.eoiu43 (ideally should be https://schema.org/SoftwareApplication)

**Youtube**
_VideoObject_
https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/31/how-adobe-created-everyday-magic.html#gs.eoita6

**Vimeo**
_VideoObject_
https://microdata-schema--theblog--adobe.hlx.page/en/publish/2020/08/31/liliane-canvas-control-plugin-designers-with-disabilities.html#gs.eohaqv

**Comment by ramboz** [comment]
Seeing the variety of embeds, maybe it would be best to inject microdata directly in the embed's output, rather than solve that clientside. Optionally also letting the customer specify the schema type as override.

**Comment by rofe** [comment]
Let's table this discussion until the topic comes back up again.

**Pull request closed without merging**
