### PR TITLE
refactor(scripts): add body class based on page type detected in url

### LINKED ISSUE #241: Add body class based on page type detected in URL
Move page-type-detection and subsequent body-class-adding from client side JS to `helix-markup.yaml`. It would be interesting to see the effect on the experience and lighthouse score if those classes were already set on the server side... currently we do:
- [page type detection here](https://github.com/adobe/theblog/blob/37fbf4f30ce15193118c5db224cefbea811a6e5a/scripts.js#L79-L109) and 
- [add the body class here](https://github.com/adobe/theblog/blob/37fbf4f30ce15193118c5db224cefbea811a6e5a/scripts/common.js#L128)

### PR DESCRIPTION
**Pull request by ramboz**
Use helix markup to inject the class on the html node so it can be read
from the scripts file and we can remove some of the JS logic.

Requires: adobe/helix-pages#382

fix #241

### CODE REVIEW

**Comment by rofe** [comment]
@ramboz I couldn't get it to work locally yet, neither on the homepage nor on a post page... it looks like `getDetectedLanguage()` and `getDetectedPageType()` always return `undefined`. I think the lookup in `LANG` and `TYPE` should probably already happen in those functions.

Btw, If you pick a branch name without a slash, we could run it directly in Helix Pages, and compare Lighthouse scores with the master branch.

**Comment by ramboz** [comment]
@rofe Will check that.

By the way, how do you test with actual content locally? at the moment I created mock data following the detected paths, but testing against real data would be more reliable.

> pick a branch name without a slash

Will do so

**Comment by ramboz** [comment]
Replaced by #266

**Comment by rofe** [comment]
Ah, I missed the fact that I need to switch the local helix-pages checkout to the `issues/241` branch to make it work, will try that. So much for comparing the approaches directly in Helix Pages 😉 

Regarding blog data: there is currently a switch in `fetchArticleIndex()` which in case of localhost loads a static queriy-index.json mimicking real data, the reason being that we are still lacking support for that in local dev.

**Comment by ramboz** [comment]
@rofe I see the switch, but any request I make returns a 404.

So either I'm missing something obvious, or there just isn't anything at the moment that would respond to any subpage with the actual content of the index.

**Comment by rofe** [comment]
Yes, the index for local dev has only just been adjusted in master (see #264). You need to pull that in to make it work on your branch, roo (or simply replace all instances of `/drafts/migrated/` with `/publish/`.

**Pull request closed without merging**
