### PR TITLE
feat(banners): styling and magic for banners

### PR DESCRIPTION
**Pull request by kptdobe**
PR for #162 

One of the styling issue is that "our" width is smaller than original site. But since UI is being changed, I did not spend to much time on it.

### CODE REVIEW

**Comment by kptdobe** [comment]
Who magically adds the width ? I do not ;)

**Comment by rofe** [comment]
Ha! This is where the "magic" is happening:
https://github.com/adobe/theblog/blob/master/head.html#L121

**Comment by kptdobe** [comment]
I would need to replace the `width=2048` on the fly. I made a quick test and the images file size (2048 and 616) are the same: 65k. Normal ?

**Comment by kptdobe** [comment]
Also, I note that all the content images (images coming from the docx / md) have a `width=2048`. Which not doing the same for those ?

**Comment by kptdobe** [comment]
And if change the window size the 616px becomes a 636px or more... 
I think I disagree with you now ;) At least, it should not be part of what I am doing but a follow up ticket to make the image lazy loader smarter for ALL images, not only the banner one. Or maybe there is something I do not see.

**Comment by rofe** [comment]
OK OK 😉 _retracting change request_

**Comment by rofe** [comment]
> And if you change the window size, the 616px becomes a 636px or more...

That's weird. But I guess we'll fix that up in the [new design](#179)

**Pull request merged**
