### PR TITLE
feat(cd): purge code cache on push to master

### PR DESCRIPTION
**Pull request by rofe**
When a code change is being pushed to master, we want to purge the cached code files to make sure the change is instantly visible.

### CODE REVIEW

**Review by tripodsan — CHANGES_REQUESTED** [review]
I don't like this too much. the files need to be purged from the inner CDN too first.
also, there is no `emergenc-button` built it, like in helix-purge. so that the CDN is not purged in case there is a backend problem.

I'd rather use helix-purge for this, or helix-bot (TBD)

**Comment by rofe** [comment]
> also, there is no emergency-button built it, like in helix-purge

For some reason, I thought `HLXPURGE` was using `helix-purge` ...

**Comment by tripodsan** [comment]
> > also, there is no emergency-button built it, like in helix-purge
> 
> For some reason, I thought `HLXPURGE` was using `helix-purge` ...

oh...yes...sorry, I did not realize.

**Review by dominique-pfister — APPROVED** [review]

**Review by tripodsan — COMMENTED** [review]
well...I don't know if this is good or bad... I think w/o checks if the backend serves the correct code, we shouldn't purge the outer CDN. but maybe that can be built into helix-purge.

as well as the delay.... @trieloff  ?

**Review by tripodsan — APPROVED** [review]
+0 (it seems I cannot remove my change-request)....

**Comment by davidnuescheler** [comment]
very practical, but i am still not sure that this (and a lot of the other purge stuff) is in the right place here. i don't have a better solution, so i would just be reluctant to have too much code like this sitting around as i think we are inevitably going to change this in the near future.

my guidance would be to be careful developing more convenience tooling around this, before we found the permanent home for that...

so +0 ;)

**Comment by rofe** [comment]
Let's try it out...

**Pull request merged**
