### PR TITLE
feat(locale): add fr/es/it support

### PR DESCRIPTION
**Pull request by kptdobe**
Index and css strings for the fr/es/it sites. I need them in master, no need to go via staging.

### CODE REVIEW

**Review by rofe — APPROVED** [review]
I'd recommend merging to `staging` instead of `master`.

**Comment by kptdobe** [comment]
I need the index in `master`, the step to staging does not bring anything.

**Comment by rofe** [comment]
> I need the index in `master`, the step to `staging` does not bring anything.

OK, as long as you merge `master` back into `staging` afterwards 😉

**Review by dominique-pfister — COMMENTED** [review]
lgtm

**Pull request merged**
