### PR TITLE
feat(feed): create Japanese feed

### PR DESCRIPTION
**Pull request by trieloff**
Simple feed for Japan, not currently linked in metadata.

Feed will be at `https://blog.adobe.com/jp-feed.xml`

### CODE REVIEW

**Comment by kptdobe** [comment]
That's not what they need. Kazuki mentioned a feed per category / topic, which would be tricky to handle because we'll need to filter per topic.

**Comment by kptdobe** [comment]
I would wait for requirements.

**Comment by trieloff** [comment]
Take a look at https://github.com/adobe/theblog/blob/master/news-feed.xml – we can filter, just not dynamically. If you give me a list of category names, I can create a bunch of feed files.

**Comment by rofe** [comment]
Fwiw, `https://trieloff-patch-1--theblog--adobe.hlx.page/jp-feed.xml` is broken:
```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Adobe Blog: Japanese</title>
  <link href="https://blog.adobe.com/jp/"/>
  <id>https://blog.adobe.com/</id>
  {
  "code": "h6tBMk4ExK9Sg0pfcHM9KHX8cHzk7n4G",
  "error": "Response not yet ready."
}
</feed>
```

**Comment by mattyroze** [comment]
@trieloff The japan team asked for the following 13 feeds... 
https://blog.adobe.com/jp/
https://blog.adobe.com/jp/topics/design.html
https://blog.adobe.com/jp/topics/photography.html
https://blog.adobe.com/jp/topics/video-audio.html
https://blog.adobe.com/jp/topics/ui-ux-web.html
https://blog.adobe.com/jp/topics/3d-ar.html
https://blog.adobe.com/jp/topics/stock.html
https://blog.adobe.com/jp/topics/ccdojo.html
https://blog.adobe.com/jp/topics/digital-transformation.html
https://blog.adobe.com/jp/topics/digital-document.html
https://blog.adobe.com/jp/topics/corporate-news.html
https://blog.adobe.com/jp/topics/education.html
https://blog.adobe.com/jp/topics/community.html

My questions:
Will this require a design element? 
Also, if we make feeds for all of these topics, will the feature simply allow a feed from any topic page?

**Comment by trieloff** [comment]
@mattyroze the current feeds are not visible in the design in any way, and not linked in the metadata. If you want to increase the visibility of these feeds, a design change would be necessary.

@rofe we could potentially use the new metadata table system on the home page, japanese home page, and category pages that have feeds to create `<link rel="alternate" type="application/rss+xml" title="Feed" href="…">` elements in the header. Most RSS feed reader won't execute the scripts on the page, so it has to be in the HTML.

**Comment by trieloff** [comment]
@stefan-guggisberg I've moved all new feeds into the `/feeds/` folder, so that your allowlist stays manageable.

**Comment by kptdobe** [comment]
We just decided to go for this list of 13 feeds. The discoverability (add `<link rel="alternate" type="application/rss+xml" title="Feed" href="…">` to the DOM) will be handled after the breaking-march release and will leverage (extend) the new metadata capability.
Assuming the feed works as expected.

**Review by kptdobe — APPROVED** [review]

**Pull request merged**
