### PR TITLE
feat(tagger): vertical tagger

### PR DESCRIPTION
**Pull request by kptdobe**
Vertical tagger based on users feedback

### CODE REVIEW

**Comment by avanishgandhi** [comment]
@kptdobe if you want me to qa test/review the vertical layout, please do let me know.

**Comment by kptdobe** [comment]
@avanishgandhi Sure, please take a look here: https://hidden-topics-test--theblog--adobe.hlx.page/tools/tagger/index.html
Feedback more than welcomed!

**Comment by avanishgandhi** [comment]
One quick feedback is at the bottom of the tool. when we choose more then hand full of tags .. the bottom tags get hidden and we can access them anymore

image

**Comment by rofe** [comment]
Fwiw, I find this layout highly confusing and personally liked the flow layout much better, but in my mind the primary UI affordance on this page should be the filter field anyway. My only feedback is that the fixed columns make it super wide, and if your window isn't at least 1700px(!) wide, the last column is breaking to the next line, which is 3(!) page-down keys below and sends the user straight to scrolling hell. I would at least make the grid flexible and adjust the column widths to 1/4 of the window width (minus gutters) so all 4 columns are always top-aligned.

**Comment by avanishgandhi** [comment]
agree with the flex grid comment.

**Comment by kptdobe** [comment]
The column wrapping was also a requirement, but probably not for a decent size screen.
There are lot of differences between the column sizes, difficult to standardise on a 1/4 per column.
I changed it now to let the flex container decide what the best distribution is: it sizes the column pretty decently according to content and it wraps the last column if width is less than 1392px. This should cover the typical minimum setup.
I also fixed what @avanishgandhi was seing.

**Pull request merged**
